import { documentHref } from '@/lib/doc-routes'
import { loadFolderDocuments } from '@/lib/workspace-library'
import { GUIDE_STEPS_COPY, GUIDE_SUGGESTED_CHAT_PROMPT, type GuideStepId } from '@/lib/inline-guide-copy'
import { WELCOME_TITLE } from '@/lib/welcome-document'

const STORAGE_KEY = 'inline_guide_v1'

export type GuideState = {
  guideCompleted?: boolean
  guidePaused?: boolean
  guideStepIndex?: number
}

type Store = Record<string, GuideState>

export type GuideStep = {
  id: GuideStepId
  title: string
  body: string
  target?: string
  centerCard?: boolean
  lightScrim?: boolean
  route?: 'dashboard' | 'history' | 'analytics' | 'settings'
  navigateToGuideDoc?: boolean
  openChat?: boolean
  suggestedPrompt?: string
}

function loadStore(): Store {
  if (typeof window === 'undefined') return {}
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    return raw ? (JSON.parse(raw) as Store) : {}
  } catch {
    return {}
  }
}

function saveStore(store: Store) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(store))
}

export function loadGuideState(workspaceId: string): GuideState {
  return loadStore()[workspaceId] ?? {}
}

export function patchGuideState(workspaceId: string, patch: Partial<GuideState>) {
  const store = loadStore()
  store[workspaceId] = { ...store[workspaceId], ...patch }
  saveStore(store)
}

export function resetGuide(workspaceId: string) {
  patchGuideState(workspaceId, {
    guideCompleted: false,
    guidePaused: false,
    guideStepIndex: 0,
  })
}

export function completeGuide(workspaceId: string) {
  patchGuideState(workspaceId, {
    guideCompleted: true,
    guidePaused: false,
    guideStepIndex: GUIDE_STEPS.length - 1,
  })
}

export const GUIDE_STEPS: GuideStep[] = GUIDE_STEPS_COPY.map(row => {
  const step: GuideStep = {
    id: row.id,
    title: row.title,
    body: row.body,
  }
  switch (row.id) {
    case 'welcome':
      step.centerCard = true
      step.route = 'dashboard'
      break
    case 'home':
      step.target = 'nav-features'
      step.route = 'dashboard'
      break
    case 'captures':
      step.target = 'nav-features'
      step.route = 'history'
      break
    case 'analytics':
      step.target = 'nav-features'
      step.route = 'analytics'
      break
    case 'settings':
      step.target = 'settings-page'
      step.route = 'settings'
      step.lightScrim = true
      break
    case 'folders':
      step.target = 'nav-folders'
      step.route = 'dashboard'
      break
    case 'auto-recap':
      step.target = 'document-editor'
      step.navigateToGuideDoc = true
      break
    case 'ask-inline':
      step.target = 'ask-inline'
      step.route = 'dashboard'
      step.openChat = true
      step.suggestedPrompt = GUIDE_SUGGESTED_CHAT_PROMPT
      break
    case 'finish':
      step.centerCard = true
      step.route = 'dashboard'
      break
  }
  return step
})

export function guideStepByIndex(index: number): GuideStep | undefined {
  return GUIDE_STEPS[index]
}

/** Welcome doc first, then any auto-generated recap, for the tour document step. */
export function resolveGuideDocumentHref(workspaceId: string): string | null {
  const docs = loadFolderDocuments().filter(d => d.workspaceId === workspaceId)
  const welcome = docs.find(
    d => d.title === WELCOME_TITLE || d.content.includes('data-inline-welcome'),
  )
  if (welcome) return documentHref(workspaceId, welcome.id)

  const recap = docs.find(d => d.autoGenerated)
  if (recap) return documentHref(workspaceId, recap.id)

  const anyDoc = docs[0]
  if (anyDoc) return documentHref(workspaceId, anyDoc.id)

  return null
}

export function isDashboardPath(pathname: string): boolean {
  return /\/app\/[^/]+\/dashboard\/?$/.test(pathname)
}

export function shouldAutoStartGuide(workspaceId: string, pathname: string): boolean {
  const state = loadGuideState(workspaceId)
  if (state.guideCompleted || state.guidePaused) return false
  return isDashboardPath(pathname)
}

export const GUIDE_RESTART_EVENT = 'inline-guide-restart'
