/**
 * Client helpers for server-backed documents stored in public.documents.
 *
 * These are intentionally similar in shape to the localStorage-backed
 * workspace-library helpers so that UI code can migrate gradually.
 */

import type { FolderDocument } from './workspace-library'

export interface ServerDocument extends Omit<FolderDocument, 'pageUrl'> {
  pageUrl: string | null
  autoGenerated: boolean
  recapStale: boolean
}

function rowToDoc(row: Record<string, unknown>): ServerDocument {
  const toNum = (v: unknown) => {
    if (typeof v === 'string') return new Date(v).getTime()
    if (typeof v === 'number') return v
    return Date.now()
  }
  return {
    id:            String(row.id ?? ''),
    workspaceId:   String(row.workspace_id ?? ''),
    folderId:      String(row.folder_id ?? 'auto-recaps'),
    title:         String(row.title ?? 'Untitled'),
    content:       typeof row.content === 'string' ? row.content : '',
    createdAt:     toNum(row.created_at),
    updatedAt:     toNum(row.updated_at),
    pageUrl:       typeof row.page_url === 'string' ? row.page_url : null,
    autoGenerated: row.auto_generated === true,
    recapStale:    row.recap_stale === true,
  }
}

export async function loadServerDocument(docId: string): Promise<ServerDocument | null> {
  try {
    const res = await fetch(`/api/library/${encodeURIComponent(docId)}`, {
      method: 'GET',
      credentials: 'include',
      cache: 'no-store',
    })
    if (!res.ok) return null
    const json = await res.json().catch(() => null) as { document?: Record<string, unknown> } | null
    if (!json?.document) return null
    return rowToDoc(json.document)
  } catch {
    return null
  }
}

export async function saveServerDocument(
  docId: string,
  patch: { title: string; content: string },
): Promise<ServerDocument | null> {
  try {
    const res = await fetch(`/api/library/${encodeURIComponent(docId)}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify(patch),
    })
    if (!res.ok) return null
    const json = await res.json().catch(() => null) as { document?: Record<string, unknown> } | null
    if (!json?.document) return null
    return rowToDoc(json.document)
  } catch {
    return null
  }
}
