import type { Note, DashboardStats } from './types'

export const MOCK_NOTES: Note[] = [
  {
    id: 'note-001',
    pageUrl: 'https://github.com/vercel/next.js/blob/canary/packages/next/src/server/app-render/app-render.tsx',
    domain: 'github.com',
    pageTitle: 'next.js/app-render.tsx at canary · vercel/next.js',
    pageContext: 'The React Framework for the Web. Used by some of the world\'s largest companies, Next.js enables you to create high-quality web applications with the full power of React.',
    content: 'Check how RSC payload is serialized here — potential perf win by chunking large payloads. Follow up with @leerob.',
    type: 'text',
    color: '#FFEB3B',
    x: 320, y: 200, width: 240, height: 160,
    tags: ['research', 'next.js', 'performance'],
    createdAt: '2026-03-19T10:30:00Z',
    updatedAt: '2026-03-19T10:35:00Z',
  },
  {
    id: 'note-002',
    pageUrl: 'https://zillow.com/homedetails/2847-maple-grove-dr-austin-tx/12345_zpid/',
    domain: 'zillow.com',
    pageTitle: '2847 Maple Grove Dr, Austin, TX 78745 | Zillow',
    pageContext: '4 beds · 2.5 baths · 2,150 sqft · $624,000 · Est. mortgage $3,890/mo',
    content: 'Good price per sqft. School district A-rated. Check HOA fees — listed as $220/mo which seems high for this area.',
    type: 'text',
    color: '#A5F3FC',
    x: 180, y: 320, width: 220, height: 140,
    lat: 30.2512, lng: -97.8081,
    tags: ['real-estate', 'austin', 'research'],
    createdAt: '2026-03-18T14:22:00Z',
    updatedAt: '2026-03-18T14:40:00Z',
  },
  {
    id: 'note-003',
    pageUrl: 'https://stripe.com/docs/api/payment_intents/create',
    domain: 'stripe.com',
    pageTitle: 'Create a PaymentIntent | Stripe API Reference',
    pageContext: 'Creates a PaymentIntent object. After the PaymentIntent is created, attach a payment method and confirm to continue the payment. Learn more about the available payment flows with the Payment Intents API.',
    content: 'Use `automatic_payment_methods: { enabled: true }` for new integrations. Deprecated `payment_method_types` array approach.',
    type: 'ai-summary',
    color: '#BBF7D0',
    x: 440, y: 150, width: 260, height: 180,
    tags: ['stripe', 'payments', 'api'],
    createdAt: '2026-03-18T09:15:00Z',
    updatedAt: '2026-03-18T09:15:00Z',
  },
  {
    id: 'note-004',
    pageUrl: 'https://linear.app/docs/api/issues',
    domain: 'linear.app',
    pageTitle: 'Issues API | Linear Docs',
    pageContext: 'The Issue object represents a task or bug in your project. Issues are the core entity in Linear and can be organized into cycles, projects, and sprints.',
    content: 'GraphQL subscription for real-time updates: `issueUpdated`. Much better than polling the REST endpoint every 5s.',
    type: 'text',
    color: '#FFEDD5',
    x: 200, y: 180, width: 240, height: 150,
    tags: ['linear', 'api', 'graphql'],
    createdAt: '2026-03-17T16:45:00Z',
    updatedAt: '2026-03-17T16:50:00Z',
  },
  {
    id: 'note-005',
    pageUrl: 'https://zillow.com/homedetails/512-cedar-ridge-ln-denver-co/67890_zpid/',
    domain: 'zillow.com',
    pageTitle: '512 Cedar Ridge Ln, Denver, CO 80203 | Zillow',
    pageContext: '3 beds · 2 baths · 1,850 sqft · $548,000 · Days on market: 12',
    content: 'Comp to the Maple Grove property. Denver market cooling — this one has been sitting for 12 days. Use as leverage.',
    type: 'text',
    color: '#FED7AA',
    x: 300, y: 250, width: 220, height: 140,
    lat: 39.7392, lng: -104.9903,
    tags: ['real-estate', 'denver', 'research'],
    createdAt: '2026-03-17T11:30:00Z',
    updatedAt: '2026-03-17T11:35:00Z',
  },
  {
    id: 'note-006',
    pageUrl: 'https://github.com/supabase/supabase/issues/21453',
    domain: 'github.com',
    pageTitle: 'RLS policy bypassed on `.rpc()` calls in certain edge cases · Issue #21453',
    pageContext: 'When calling an RPC function with security definer, the RLS policies on underlying tables are bypassed if the function was created before the policy.',
    content: 'CRITICAL: Affects our auth layer. Workaround: recreate affected functions. Patch expected in v2.44.0.',
    type: 'text',
    color: '#FECACA',
    x: 150, y: 280, width: 260, height: 170,
    tags: ['supabase', 'security', 'bug'],
    createdAt: '2026-03-17T08:00:00Z',
    updatedAt: '2026-03-17T08:05:00Z',
  },
  {
    id: 'note-007',
    pageUrl: 'https://vercel.com/docs/functions/edge-functions',
    domain: 'vercel.com',
    pageTitle: 'Edge Functions | Vercel Docs',
    pageContext: 'Edge Functions allow you to deliver dynamic, personalized content with the performance of a static site. They run globally on the Edge Network, close to your users.',
    content: 'Cold start is ~0ms vs ~400ms for serverless. 128MB memory limit is the tradeoff. Good for auth middleware, A/B testing, and geo-routing.',
    type: 'ai-summary',
    color: '#BBF7D0',
    x: 280, y: 200, width: 250, height: 160,
    tags: ['vercel', 'edge', 'performance'],
    createdAt: '2026-03-16T14:20:00Z',
    updatedAt: '2026-03-16T14:20:00Z',
  },
  {
    id: 'note-008',
    pageUrl: 'https://github.com/pmndrs/zustand',
    domain: 'github.com',
    pageTitle: 'pmndrs/zustand: Bear necessities for state management in React',
    pageContext: 'A small, fast and scalable bearbones state-management solution using simplified flux principles. Has a comfy API based on hooks.',
    content: 'Consider replacing Redux with Zustand for the extension popup. Bundle size goes from 47kb to 3kb.',
    type: 'text',
    color: '#FFEB3B',
    x: 360, y: 180, width: 220, height: 140,
    tags: ['react', 'state-management', 'zustand'],
    createdAt: '2026-03-16T10:15:00Z',
    updatedAt: '2026-03-16T10:20:00Z',
  },
  {
    id: 'note-009',
    pageUrl: 'https://zillow.com/homedetails/9134-oak-valley-rd-seattle-wa/11111_zpid/',
    domain: 'zillow.com',
    pageTitle: '9134 Oak Valley Rd, Seattle, WA 98115 | Zillow',
    pageContext: '5 beds · 3 baths · 2,800 sqft · $985,000 · Sold 3 times in last 10 years',
    content: 'Seattle Eastside getting expensive. This one is at the top of our budget. Walkability score 72 is decent. Check commute to downtown.',
    type: 'text',
    color: '#DDD6FE',
    x: 200, y: 300, width: 230, height: 150,
    lat: 47.6892, lng: -122.3210,
    tags: ['real-estate', 'seattle', 'research'],
    createdAt: '2026-03-15T15:45:00Z',
    updatedAt: '2026-03-15T15:55:00Z',
  },
  {
    id: 'note-010',
    pageUrl: 'https://stripe.com/docs/connect/charges-transfers',
    domain: 'stripe.com',
    pageTitle: 'Charges and Transfers | Stripe Connect',
    pageContext: 'With Connect, you can move money from a customer to a connected account, and collect fees for doing so. There are three approaches to creating charges.',
    content: '3 models: Direct, Destination, Separate charges+transfers. We need Destination for marketplace. Revisit fee structure.',
    type: 'canvas',
    color: '#A5F3FC',
    x: 250, y: 200, width: 260, height: 180,
    tags: ['stripe', 'connect', 'marketplace'],
    createdAt: '2026-03-15T11:00:00Z',
    updatedAt: '2026-03-15T11:30:00Z',
  },
  {
    id: 'note-011',
    pageUrl: 'https://news.ycombinator.com/item?id=39847362',
    domain: 'news.ycombinator.com',
    pageTitle: 'Ask HN: What\'s your approach to LLM rate limiting in production?',
    pageContext: 'We\'re processing about 100k requests/day to OpenAI. Hitting rate limits even on Tier 4. Looking for architectural approaches.',
    content: 'Top answer: token bucket per user + global leaky bucket. Use Redis. Fallback to smaller model (GPT-4o-mini) when rate limited.',
    type: 'ai-summary',
    color: '#BBF7D0',
    x: 320, y: 170, width: 260, height: 170,
    tags: ['llm', 'architecture', 'production'],
    createdAt: '2026-03-14T19:30:00Z',
    updatedAt: '2026-03-14T19:30:00Z',
  },
  {
    id: 'note-012',
    pageUrl: 'https://linear.app/changelog/2026-02',
    domain: 'linear.app',
    pageTitle: 'Changelog · February 2026 | Linear',
    pageContext: 'New: Triage mode for issues, Bulk AI labeling, Custom views with saved filters, Timeline view improvements.',
    content: 'Triage mode is exactly what we need for the client project. Enable it on the workspace and set up automation rules.',
    type: 'text',
    color: '#FFEDD5',
    x: 240, y: 220, width: 230, height: 145,
    tags: ['linear', 'productivity', 'tools'],
    createdAt: '2026-03-14T10:00:00Z',
    updatedAt: '2026-03-14T10:05:00Z',
  },
]

// Generate 30 days of capture history
function generateCaptureHistory(): { date: string; count: number }[] {
  const history = []
  const now = new Date('2026-03-20')
  for (let i = 29; i >= 0; i--) {
    const d = new Date(now)
    d.setDate(d.getDate() - i)
    const dateStr = d.toISOString().split('T')[0]
    // Simulate realistic usage with weekday peaks
    const dayOfWeek = d.getDay()
    const isWeekend = dayOfWeek === 0 || dayOfWeek === 6
    const base = isWeekend ? 2 : 6
    const variance = Math.floor(Math.random() * 5)
    history.push({ date: dateStr, count: base + variance })
  }
  return history
}

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  notesThisWeek: 18,
  notesThisWeekDelta: 12,
  totalNotes: 247,
  totalDomains: 34,
  aiQueriesRun: 89,
  streakDays: 14,
  captureHistory: generateCaptureHistory(),
  topDomains: [
    { domain: 'github.com', count: 82, percentage: 33, lastVisited: '2026-03-20T10:30:00Z' },
    { domain: 'zillow.com', count: 54, percentage: 22, lastVisited: '2026-03-19T15:20:00Z' },
    { domain: 'stripe.com', count: 31, percentage: 13, lastVisited: '2026-03-18T11:00:00Z' },
    { domain: 'linear.app', count: 28, percentage: 11, lastVisited: '2026-03-17T16:45:00Z' },
    { domain: 'vercel.com', count: 22, percentage: 9, lastVisited: '2026-03-16T14:20:00Z' },
    { domain: 'news.ycombinator.com', count: 16, percentage: 6, lastVisited: '2026-03-14T19:30:00Z' },
    { domain: 'other', count: 14, percentage: 6, lastVisited: '2026-03-13T08:00:00Z' },
  ],
}
