import type { SupabaseClient } from '@supabase/supabase-js'
import { chunkText, normalizeText } from './text'
import { embedTexts } from './embeddings'

/**
 * Server-side indexing pipeline: chunk → embed → upsert into
 * public.workspace_embeddings. All writes go through the caller's RLS-scoped
 * Supabase client, so a user can only ever index their own rows.
 */

export type EmbeddingSourceType = 'note' | 'document' | 'page' | 'recap' | 'annotation'

export type IndexableSource = {
  sourceType: EmbeddingSourceType
  sourceId: string
  workspaceId: string | null
  pageUrl?: string | null
  pageTitle?: string | null
  domain?: string | null
  text: string
  metadata?: Record<string, unknown>
}

export type IndexResult = {
  indexed: number
  skipped: number
  errors: string[]
}

/* eslint-disable @typescript-eslint/no-explicit-any */
type AnyClient = SupabaseClient<any, any, any>
/* eslint-enable @typescript-eslint/no-explicit-any */

/** pgvector literal for Supabase upserts — must be `[n,n,...]`, not JSON-quoted. */
function toPgVector(values: number[]): string {
  return `[${values.join(',')}]`
}

/**
 * Replace all chunks for one source with freshly embedded chunks.
 * Skips silently when there is nothing meaningful to embed.
 */
export async function upsertEmbeddingChunks(
  supabase: AnyClient,
  userId: string,
  source: IndexableSource,
): Promise<IndexResult> {
  const result: IndexResult = { indexed: 0, skipped: 0, errors: [] }
  const text = normalizeText(source.text)

  // Always clear stale chunks first so deleted/emptied content stops matching.
  const { error: delErr } = await supabase
    .from('workspace_embeddings')
    .delete()
    .eq('user_id', userId)
    .eq('source_type', source.sourceType)
    .eq('source_id', source.sourceId)
  if (delErr) result.errors.push(`delete: ${delErr.message}`)

  if (!text || text.length < 12) {
    result.skipped += 1
    return result
  }

  const chunks = chunkText(text)
  if (chunks.length === 0) {
    result.skipped += 1
    return result
  }

  let embeddings: number[][] | null = null
  try {
    embeddings = await embedTexts(chunks.map(c => c.text))
  } catch (err) {
    result.errors.push(`embed: ${(err as Error)?.message ?? 'failed'}`)
    return result
  }
  if (!embeddings) {
    result.errors.push('embed: no AI API key configured')
    return result
  }

  const now = new Date().toISOString()
  const rows = chunks.map((chunk, i) => ({
    user_id: userId,
    workspace_id: source.workspaceId ?? '',
    source_type: source.sourceType,
    source_id: source.sourceId,
    page_url: source.pageUrl ?? null,
    page_title: source.pageTitle ?? null,
    domain: source.domain ?? null,
    chunk_text: chunk.text,
    chunk_index: chunk.index,
    metadata: source.metadata ?? {},
    embedding: toPgVector(embeddings[i]),
    updated_at: now,
  }))

  const { error: insErr } = await supabase
    .from('workspace_embeddings')
    .upsert(rows, { onConflict: 'user_id,source_type,source_id,chunk_index' })
  if (insErr) {
    result.errors.push(`upsert: ${insErr.message}`)
    return result
  }

  result.indexed = rows.length
  return result
}

type NoteRow = {
  id: string
  workspace_id: string | null
  page_url: string | null
  page_title: string | null
  domain: string | null
  content: string | null
  type: string | null
  tags: string[] | null
}

export function noteToSource(note: NoteRow): IndexableSource {
  return {
    sourceType: 'note',
    sourceId: note.id,
    workspaceId: note.workspace_id,
    pageUrl: note.page_url,
    pageTitle: note.page_title,
    domain: note.domain,
    text: note.content ?? '',
    metadata: { noteType: note.type ?? 'text', tags: note.tags ?? [] },
  }
}

type DocumentRow = {
  id: string
  workspace_id: string | null
  page_url: string | null
  title: string | null
  content: unknown
  auto_generated: boolean | null
}

export function documentToSource(doc: DocumentRow): IndexableSource {
  const body = typeof doc.content === 'string' ? doc.content : JSON.stringify(doc.content ?? '')
  let domain: string | null = null
  if (doc.page_url) {
    try { domain = new URL(doc.page_url).hostname } catch { /* not a URL */ }
  }
  return {
    sourceType: doc.auto_generated ? 'recap' : 'document',
    sourceId: doc.id,
    workspaceId: doc.workspace_id,
    pageUrl: doc.page_url,
    pageTitle: doc.title,
    domain,
    text: `${doc.title ?? ''}\n\n${body}`,
    metadata: { autoGenerated: Boolean(doc.auto_generated) },
  }
}

/** Index a single note row by id (used by /api/clip and /api/ai/index). */
export async function indexNoteById(
  supabase: AnyClient,
  userId: string,
  noteId: string,
): Promise<IndexResult> {
  const { data, error } = await supabase
    .from('notes')
    .select('id, workspace_id, page_url, page_title, domain, content, type, tags')
    .eq('id', noteId)
    .maybeSingle()
  if (error || !data) return { indexed: 0, skipped: 1, errors: error ? [error.message] : [] }
  return upsertEmbeddingChunks(supabase, userId, noteToSource(data as NoteRow))
}

/** Index a single document row by id (library docs + auto-recaps). */
export async function indexDocumentById(
  supabase: AnyClient,
  userId: string,
  docId: string,
): Promise<IndexResult> {
  const { data, error } = await supabase
    .from('documents')
    .select('id, workspace_id, page_url, title, content, auto_generated')
    .eq('id', docId)
    .maybeSingle()
  if (error || !data) return { indexed: 0, skipped: 1, errors: error ? [error.message] : [] }
  return upsertEmbeddingChunks(supabase, userId, documentToSource(data as DocumentRow))
}

/** Index every note mirrored for one page (called after annotation saves). */
export async function indexPageNotes(
  supabase: AnyClient,
  userId: string,
  workspaceId: string | null,
  pageUrl: string,
): Promise<IndexResult> {
  let query = supabase
    .from('notes')
    .select('id, workspace_id, page_url, page_title, domain, content, type, tags')
    .eq('user_id', userId)
    .eq('page_url', pageUrl)
    .limit(200)
  if (workspaceId) query = query.eq('workspace_id', workspaceId)

  const { data, error } = await query
  if (error) return { indexed: 0, skipped: 0, errors: [error.message] }

  const total: IndexResult = { indexed: 0, skipped: 0, errors: [] }
  for (const note of (data ?? []) as NoteRow[]) {
    const r = await upsertEmbeddingChunks(supabase, userId, noteToSource(note))
    total.indexed += r.indexed
    total.skipped += r.skipped
    total.errors.push(...r.errors)
  }
  return total
}

/**
 * Backfill: index all notes + documents in a workspace that have no chunks
 * yet. Batched so a single call stays within serverless limits; returns
 * `remaining` so the caller can loop.
 */
export async function backfillWorkspace(
  supabase: AnyClient,
  userId: string,
  workspaceId: string,
  batchSize = 20,
): Promise<IndexResult & { remaining: number }> {
  const total: IndexResult & { remaining: number } = { indexed: 0, skipped: 0, errors: [], remaining: 0 }

  const { data: existing } = await supabase
    .from('workspace_embeddings')
    .select('source_type, source_id')
    .eq('user_id', userId)
    .limit(5000)

  const indexedNotes = new Set<string>()
  const indexedDocs = new Set<string>()
  for (const row of (existing ?? []) as { source_type: string; source_id: string }[]) {
    if (row.source_type === 'note') indexedNotes.add(row.source_id)
    else indexedDocs.add(row.source_id)
  }

  // Index all user captures — workspace_id on notes is often legacy ('dashboard', etc.).
  const { data: notes } = await supabase
    .from('notes')
    .select('id, workspace_id, page_url, page_title, domain, content, type, tags')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(500)

  const { data: docs } = await supabase
    .from('documents')
    .select('id, workspace_id, page_url, title, content, auto_generated')
    .eq('user_id', userId)
    .order('updated_at', { ascending: false })
    .limit(200)

  const pendingNotes = ((notes ?? []) as NoteRow[]).filter(n => !indexedNotes.has(n.id))
  const pendingDocs = ((docs ?? []) as DocumentRow[]).filter(d => !indexedDocs.has(d.id))

  let processed = 0
  for (const note of pendingNotes) {
    if (processed >= batchSize) break
    const scoped = { ...note, workspace_id: note.workspace_id ?? workspaceId }
    const r = await upsertEmbeddingChunks(supabase, userId, noteToSource(scoped))
    total.indexed += r.indexed
    total.skipped += r.skipped
    total.errors.push(...r.errors)
    processed += 1
  }
  for (const doc of pendingDocs) {
    if (processed >= batchSize) break
    const r = await upsertEmbeddingChunks(supabase, userId, documentToSource(doc))
    total.indexed += r.indexed
    total.skipped += r.skipped
    total.errors.push(...r.errors)
    processed += 1
  }

  total.remaining = Math.max(0, pendingNotes.length + pendingDocs.length - processed)
  return total
}

/** Index any unembedded notes/documents for a workspace before RAG queries. */
export async function ensureWorkspaceIndexed(
  supabase: AnyClient,
  userId: string,
  workspaceId: string,
  { maxBatches = 12, batchSize = 30 }: { maxBatches?: number; batchSize?: number } = {},
): Promise<IndexResult> {
  const total: IndexResult = { indexed: 0, skipped: 0, errors: [] }

  for (let i = 0; i < maxBatches; i++) {
    const batch = await backfillWorkspace(supabase, userId, workspaceId, batchSize)
    total.indexed += batch.indexed
    total.skipped += batch.skipped
    total.errors.push(...batch.errors)
    if (batch.remaining === 0) break
    if (batch.indexed === 0 && batch.errors.length > 0) break
  }

  return total
}
