import { useEffect, useState } from 'react'
import './App.css'
import { loadSettings, saveSettings, purgeLegacySecrets } from './lib/extensionSettings'
import { INLINE_VOICE_PRESETS, DEFAULT_INLINE_VOICE_ID } from './lib/inlineVoicePresets'

/**
 * Extension popup. Session and workspace are synced automatically from the
 * dashboard (INLINE_SYNC_AUTH) — no API keys are ever entered or stored here.
 * Read-aloud uses the dashboard's secure server-side TTS proxy.
 */

function looksLikeJwt(token: string): boolean {
  const parts = token.split('.')
  return parts.length === 3 && parts.every(p => p.length > 0)
}

function App() {
  const [apiBase, setApiBase] = useState('http://localhost:3000')
  const [token, setToken] = useState('')
  const [hasWorkspace, setHasWorkspace] = useState(false)
  const [voiceId, setVoiceId] = useState(DEFAULT_INLINE_VOICE_ID)
  const [saved, setSaved] = useState(false)

  useEffect(() => {
    void purgeLegacySecrets()
    void loadSettings().then(s => {
      setApiBase(s.apiBaseUrl)
      setToken(s.accessToken)
      setVoiceId(s.voiceId)
    })
    chrome.storage.local.get(['inlineActiveWorkspaceId'], r => {
      setHasWorkspace(typeof r.inlineActiveWorkspaceId === 'string' && r.inlineActiveWorkspaceId.trim().length > 0)
    })
  }, [])

  const signedIn = looksLikeJwt(token)
  const dashboardUrl = apiBase.replace(/\/$/, '')

  return (
    <div className="popup-wrap">
      <div className="popup-brand">
        <div className="popup-brand-icon"><span /></div>
        <div>
          <h1 className="popup-title">Inline</h1>
          <p className="popup-tagline">Your memory layer for the web</p>
        </div>
      </div>

      <div className={`popup-status ${signedIn ? 'is-connected' : 'is-disconnected'}`}>
        <span className="popup-status-dot" aria-hidden="true" />
        <div className="popup-status-text">
          {signedIn ? (
            <>
              <strong>Connected</strong>
              <span>{hasWorkspace ? 'Personal Workspace' : 'Connected to cloud'}</span>
            </>
          ) : (
            <>
              <strong>Not signed in</strong>
              <span>Local only. Sign in to sync captures across devices.</span>
            </>
          )}
        </div>
      </div>

      <label className="popup-label" htmlFor="popup-voice">Read-aloud voice</label>
      <select
        id="popup-voice"
        className="popup-input"
        value={voiceId}
        onChange={e => setVoiceId(e.target.value)}
      >
        {INLINE_VOICE_PRESETS.map(v => (
          <option key={v.id} value={v.id}>
            {v.name} - {v.subtitle}
          </option>
        ))}
      </select>
      <p className="popup-hint">
        Voice audio is generated by Inline&apos;s secure server. If the cloud voice is
        unavailable, the browser voice is used automatically.
      </p>

      <button
        type="button"
        className="popup-save"
        onClick={async () => {
          await saveSettings({ voiceId })
          setSaved(true)
          setTimeout(() => setSaved(false), 1500)
        }}
      >
        Save settings
      </button>
      {saved && <p className="popup-saved" role="status">Saved.</p>}

      <button
        type="button"
        className="popup-link-btn"
        onClick={() => { window.open(dashboardUrl + '/app/dashboard', '_blank') }}
      >
        Open Inline dashboard
      </button>
    </div>
  )
}

export default App
