'use client'

import { cn } from '@/lib/utils'

interface DocumentViewHeaderProps {
  title: string
  autoGenerated?: boolean
  editable?: boolean
  onTitleChange?: (value: string) => void
  onTitleBlur?: () => void
}

export default function DocumentViewHeader({
  title,
  autoGenerated = false,
  editable = true,
  onTitleChange,
  onTitleBlur,
}: DocumentViewHeaderProps) {
  const displayTitle = title.trim() || 'Untitled'

  return (
    <header className="mb-8 space-y-3">
      {editable ? (
        <input
          value={title}
          onChange={e => onTitleChange?.(e.target.value)}
          onBlur={onTitleBlur}
          className="w-full border-none bg-transparent text-3xl font-semibold tracking-tight text-foreground outline-none placeholder:text-muted-foreground/40"
          placeholder="Untitled"
          aria-label="Document title"
        />
      ) : (
        <h1 className="text-3xl font-semibold tracking-tight text-foreground leading-tight">
          {displayTitle}
        </h1>
      )}

      {autoGenerated && (
        <p className={cn('text-sm text-muted-foreground')}>
          A detailed log of what you captured on the source page. Editable like any document — new captures still append on refresh.
        </p>
      )}
    </header>
  )
}
