'use client'

import Link from 'next/link'
import { ChevronRight, ExternalLink, Sparkles } from 'lucide-react'
import { formatRelativeUpdated } from '@/lib/recap-meta'
import { workspacePath } from '@/lib/workspace-routes'
import type { ReactNode } from 'react'

interface DocumentTopBarProps {
  workspaceId: string
  workspaceName: string
  folderId: string
  folderName: string
  title: string
  autoGenerated?: boolean
  pageUrl?: string
  updatedAt?: number
  captureTags?: string[]
  /** e.g. synthesis ROI ring — pinned to the right on large screens. */
  trailing?: ReactNode
  actions?: ReactNode
}

export default function DocumentTopBar({
  workspaceId,
  workspaceName,
  folderId,
  folderName,
  title,
  autoGenerated = false,
  pageUrl,
  updatedAt,
  captureTags = [],
  trailing,
  actions,
}: DocumentTopBarProps) {
  const displayTitle = title.trim() || 'Untitled'
  const folderHref = workspacePath(workspaceId, 'folder', folderId)
  const dashboardHref = workspacePath(workspaceId, 'dashboard')

  const showMetaRow = autoGenerated

  return (
    <div className="w-full bg-background pb-4 pt-5 lg:pb-5">
      <nav
        aria-label="Breadcrumb"
        className="flex items-center justify-between gap-4 px-4 sm:px-6 lg:px-8"
      >
        <div className="flex min-w-0 flex-wrap items-center gap-1.5 text-sm">
          <Link
            href={dashboardHref}
            className="shrink-0 text-muted-foreground transition-colors hover:text-foreground"
          >
            {workspaceName}
          </Link>
          <ChevronRight className="h-3.5 w-3.5 shrink-0 text-muted-foreground/50" aria-hidden />
          <Link
            href={folderHref}
            className="shrink-0 text-muted-foreground transition-colors hover:text-foreground"
          >
            {folderName}
          </Link>
          <ChevronRight className="h-3.5 w-3.5 shrink-0 text-muted-foreground/50" aria-hidden />
          <span className="min-w-0 truncate font-medium text-foreground">{displayTitle}</span>
        </div>
        {(actions || trailing) && (
          <div className="flex shrink-0 items-center gap-1.5">
            {trailing}
            {actions}
          </div>
        )}
      </nav>

      {showMetaRow && (
        <div className="mt-3 flex flex-wrap items-center gap-2 px-4 sm:px-6 lg:px-8">
          <span className="inline-flex items-center gap-1.5 rounded-full border border-amber-200 bg-amber-50 px-2.5 py-1 text-[11px] font-medium text-amber-800 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-300">
            <Sparkles className="h-3 w-3" aria-hidden />
            Auto-recap
          </span>
          {captureTags.map(tag => (
            <span
              key={tag}
              className="inline-flex rounded-full border border-border bg-muted/50 px-2.5 py-1 text-[11px] font-medium text-muted-foreground capitalize"
            >
              {tag}
            </span>
          ))}
          {pageUrl && (
            <a
              href={pageUrl}
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center gap-1.5 text-xs font-medium text-primary transition-opacity hover:opacity-80"
            >
              <ExternalLink className="h-3 w-3" aria-hidden />
              Open source page
            </a>
          )}
          {updatedAt != null && (
            <span className="text-xs text-muted-foreground">
              Updated {formatRelativeUpdated(updatedAt)}
            </span>
          )}
        </div>
      )}
    </div>
  )
}
