export { default as ExtensionAskPanelMock } from './ExtensionAskPanelMock'
export { default as ExtensionDockMock } from './ExtensionDockMock'
export { default as ExtensionDockSceneMock } from './ExtensionDockSceneMock'
export { default as ExtensionRefreshRoutineMock } from './ExtensionRefreshRoutineMock'
export { default as ExtensionRecapResultMock } from './ExtensionRecapResultMock'
export { default as ExtensionToolbarMock } from './ExtensionToolbarMock'
export { default as DashboardCapturesMock } from './DashboardCapturesMock'
export { default as WorkspaceChatMock } from './WorkspaceChatMock'
export type { WorkspaceChatScenario } from './WorkspaceChatMock'
export { default as WorkspaceDashboardPreviewMock } from './WorkspaceDashboardPreviewMock'
export * from './sampleData'
