'use client'

import { useEffect, useState, useCallback, useRef, useMemo } from 'react'
import Link from 'next/link'
import { useParams, usePathname, useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { getWorkspaceName } from '@/lib/workspaces'
import {
  getDocumentById,
  upsertFolderDocument,
  deleteFolderDocument,
  type FolderDocument,
} from '@/lib/workspace-library'
import { findFolder, loadWorkspaceFolders } from '@/lib/workspace-folders'
import { isPinnedDocument, togglePinnedDocument } from '@/lib/dashboard-favorites'
import FolderDocumentEditor from '@/components/documents/FolderDocumentEditor'
import DocumentViewHeader from '@/components/documents/DocumentViewHeader'
import DocumentHeaderActions from '@/components/documents/DocumentHeaderActions'
import { normalizeRecapContent, regenerateRecapFromNotes, regenerateRecapFromNotesAsync } from '@/lib/auto-recap'
import { buildRecapHeaderTags } from '@/lib/recap-meta'
import { useRecapNotes } from '@/lib/use-recap-notes'
import RecapContextPanel from '@/components/documents/RecapContextPanel'
import RecapFooterActions from '@/components/documents/RecapFooterActions'
import RecapDocEnhancements from '@/components/documents/RecapDocEnhancements'
import { useConfirm, useToast } from '@/components/ui/notifications'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import {
  ArrowLeft, Clock, Star, Share2, MessageCircle,
  X, Send, MoreHorizontal, Link2, Trash2,
} from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { cn } from '@/lib/utils'
import { resolveWorkspaceIdFromBrowserPath, workspacePath } from '@/lib/workspace-routes'

function loadSidebarFolderName(workspaceId: string, folderId: string): string | null {
  if (typeof window === 'undefined') return null
  const f = findFolder(loadWorkspaceFolders(), workspaceId, folderId)
  return f?.name ?? null
}

interface Comment {
  id: string
  author: string
  text: string
  time: number
}

export default function FolderDocumentEditorPage() {
  const params = useParams()
  const pathname = usePathname()
  const router = useRouter()
  const confirm = useConfirm()
  const toast = useToast()
  const workspaceId = resolveWorkspaceIdFromBrowserPath(pathname)
  const folderId     = Array.isArray(params.folderId)     ? params.folderId[0]!     : (params.folderId     as string)
  const documentId   = Array.isArray(params.documentId)   ? params.documentId[0]!   : (params.documentId   as string)
  const workspaceName = getWorkspaceName(workspaceId)
  const [folderName, setFolderName] = useState('Folder')

  const [doc,        setDoc]        = useState<FolderDocument | null>(null)
  const [title,      setTitle]      = useState('')
  const [savedFlash, setSavedFlash] = useState(false)
  const [isFav,      setIsFav]      = useState(false)

  const [showComments,  setShowComments]  = useState(false)
  const [showShare,     setShowShare]     = useState(false)
  const [comments,      setComments]      = useState<Comment[]>([])
  const [commentDraft,  setCommentDraft]  = useState('')
  const [linkCopied,    setLinkCopied]    = useState(false)
  const [regenerating,  setRegenerating]  = useState(false)
  const [panelCollapsed, setPanelCollapsed] = useState(false)
  const [recapMenuOpen, setRecapMenuOpen] = useState(false)
  const commentInputRef = useRef<HTMLInputElement>(null)

  const { notes: pageNotes, loading: notesLoading } = useRecapNotes(workspaceId, doc?.pageUrl)

  useEffect(() => {
    setFolderName(loadSidebarFolderName(workspaceId, folderId) ?? 'Folder')
    const sync = () => setFolderName(loadSidebarFolderName(workspaceId, folderId) ?? 'Folder')
    window.addEventListener('inline-folders-changed', sync)
    const onStorage = (e: StorageEvent) => { if (e.key === 'inline-folders') sync() }
    window.addEventListener('storage', onStorage)
    return () => {
      window.removeEventListener('inline-folders-changed', sync)
      window.removeEventListener('storage', onStorage)
    }
  }, [workspaceId, folderId])

  useEffect(() => {
    const d = getDocumentById(documentId)
    if (!d || d.workspaceId !== workspaceId || d.folderId !== folderId) { setDoc(null); return }
    setDoc(d)
    setTitle(d.title)
    setIsFav(isPinnedDocument(workspaceId, documentId))
    // Load comments from local storage
    try {
      const saved = localStorage.getItem(`doc-comments-${documentId}`)
      if (saved) setComments(JSON.parse(saved))
    } catch { /* ignore */ }
  }, [documentId, workspaceId, folderId])

  const persist = useCallback((nextTitle: string, nextContent: string) => {
    if (!doc) return
    const updated: FolderDocument = {
      ...doc,
      title:     nextTitle.trim() || 'Untitled',
      content:   nextContent,
      updatedAt: Date.now(),
      recapStale: doc.autoGenerated ? true : doc.recapStale,
    }
    upsertFolderDocument(updated)
    setDoc(updated)
    setSavedFlash(true)
    setTimeout(() => setSavedFlash(false), 1200)
  }, [doc])

  const handleContentChange = useCallback((html: string) => {
    if (!doc) return
    persist(title, html)
  }, [doc, title, persist])

  const handleRegenerate = useCallback(async () => {
    if (!doc?.pageUrl) return
    setRegenerating(true)
    try {
      const updated = await regenerateRecapFromNotesAsync(doc, workspaceName, pageNotes)
      upsertFolderDocument(updated)
      setDoc(updated)
      setTitle(updated.title)
    } finally {
      setRegenerating(false)
    }
  }, [doc, workspaceName, pageNotes])

  const captureTags = useMemo(
    () => (doc?.pageUrl ? buildRecapHeaderTags(doc.pageUrl, pageNotes) : []),
    [doc?.pageUrl, pageNotes],
  )

  const isAutoRecap = !!doc?.autoGenerated
  const editorContent = useMemo(() => {
    if (!doc) return ''
    return isAutoRecap ? normalizeRecapContent(doc.content, pageNotes) : doc.content
  }, [doc, isAutoRecap, pageNotes])

  useEffect(() => {
    if (!doc?.autoGenerated || notesLoading || pageNotes.length === 0) return
    const normalized = normalizeRecapContent(doc.content, pageNotes)
    if (normalized === doc.content) return
    const updated = { ...doc, content: normalized }
    upsertFolderDocument(updated)
    setDoc(updated)
  }, [doc, pageNotes, notesLoading])

  function addComment() {
    if (!commentDraft.trim()) return
    const next = [...comments, {
      id: crypto.randomUUID(),
      author: 'You',
      text: commentDraft.trim(),
      time: Date.now(),
    }]
    setComments(next)
    setCommentDraft('')
    localStorage.setItem(`doc-comments-${documentId}`, JSON.stringify(next))
    commentInputRef.current?.focus()
  }

  function deleteComment(id: string) {
    const next = comments.filter(c => c.id !== id)
    setComments(next)
    localStorage.setItem(`doc-comments-${documentId}`, JSON.stringify(next))
  }

  async function copyDocLink() {
    try {
      await navigator.clipboard.writeText(window.location.href)
      setLinkCopied(true)
      setTimeout(() => setLinkCopied(false), 1800)
    } catch {
      setLinkCopied(false)
    }
  }

  function toggleFavorite() {
    togglePinnedDocument(workspaceId, documentId)
    setIsFav(isPinnedDocument(workspaceId, documentId))
  }

  async function handleDeleteDocument() {
    const ok = await confirm({
      title: 'Delete this document?',
      description: 'This permanently removes the document. This cannot be undone.',
      confirmLabel: 'Delete',
      destructive: true,
    })
    if (!ok) return
    deleteFolderDocument(documentId)
    toast.success('Document deleted')
    router.push(workspacePath(workspaceId, 'folder', folderId))
  }

  const timeSince = (ms: number) => {
    const diff = Date.now() - ms
    if (diff < 60000) return 'just now'
    if (diff < 3600000) return `${Math.floor(diff / 60000)}m ago`
    if (diff < 86400000) return `${Math.floor(diff / 3600000)}h ago`
    return new Date(ms).toLocaleDateString()
  }

  if (!doc) {
    return (
      <div className="min-h-full bg-white p-8">
        <p className="text-slate-500">Document not found.</p>
        <Link href={workspacePath(workspaceId, 'folder', folderId)} className="text-[#37352F] text-sm mt-4 inline-block cursor-pointer">
          &larr; Back to folder
        </Link>
      </div>
    )
  }

  return (
    <div className="flex h-full min-h-0 flex-col overflow-hidden bg-white">
      {/* ── Top nav bar ── */}
      <div className="flex items-center justify-between px-5 py-3 border-b border-slate-200 bg-white shrink-0">
        <div className="flex items-center gap-3 min-w-0">
          <Link
            href={workspacePath(workspaceId, 'folder', folderId)}
            className="flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-800 transition-colors cursor-pointer shrink-0"
          >
            <ArrowLeft className="w-4 h-4" />
          </Link>

          <div className="w-8 h-8 rounded-lg bg-[#EDEBE8] border border-[#E3E2DE] flex items-center justify-center shrink-0">
            <span className="text-[#37352F] text-sm font-bold">{(title || 'U')[0].toUpperCase()}</span>
          </div>

          <div className="min-w-0">
            <p className="text-sm font-semibold text-slate-800 truncate">{title || 'Untitled'}</p>
            <p className="text-[11px] text-slate-400">
              <Link href={workspacePath(workspaceId, 'dashboard')} className="hover:text-slate-600 transition-colors">{workspaceName}</Link>
              {' · '}
              <Link href={workspacePath(workspaceId, 'folder', folderId)} className="hover:text-slate-600 transition-colors">{folderName}</Link>
            </p>
          </div>
        </div>

        <div className="flex items-center gap-1.5">
          <span className={cn(
            'text-xs px-2 py-0.5 rounded-full transition-all',
            savedFlash ? 'text-emerald-600 bg-emerald-50' : 'text-slate-400'
          )}>
            {savedFlash ? 'Saved' : <><Clock className="w-3 h-3 inline-block mr-1" />Auto-saving</>}
          </span>

          <button
            type="button"
            onClick={() => setShowComments(v => !v)}
            className={cn(
              'w-8 h-8 rounded-lg flex items-center justify-center transition-colors cursor-pointer',
              showComments ? 'bg-[#F1F1EF] text-[#37352F]' : 'text-slate-400 hover:bg-slate-100 hover:text-slate-600'
            )}
            title="Comments"
            hidden={isAutoRecap}
          >
            <MessageCircle className="w-4 h-4" />
          </button>

          <button
            type="button"
            onClick={() => setShowShare(true)}
            className="w-8 h-8 rounded-lg flex items-center justify-center text-slate-400 hover:bg-slate-100 hover:text-slate-600 transition-colors cursor-pointer"
            title="Share"
            aria-label="Share document"
            hidden={isAutoRecap}
          >
            <Share2 className="w-4 h-4" />
          </button>

          <button
            type="button"
            onClick={toggleFavorite}
            className={cn(
              'w-8 h-8 rounded-lg flex items-center justify-center transition-colors cursor-pointer',
              isFav ? 'text-amber-500' : 'text-slate-400 hover:bg-slate-100 hover:text-slate-600'
            )}
            title={isFav ? 'Remove from favorites' : 'Add to favorites'}
            aria-label={isFav ? 'Remove from favorites' : 'Add to favorites'}
            aria-pressed={isFav}
            hidden={isAutoRecap}
          >
            <Star className="w-4 h-4" fill={isFav ? 'currentColor' : 'none'} />
          </button>

          {!isAutoRecap && (
          <DropdownMenu>
            <DropdownMenuTrigger
              className="w-8 h-8 rounded-lg flex items-center justify-center text-slate-400 hover:bg-slate-100 hover:text-slate-600 transition-colors cursor-pointer outline-none"
              aria-label="Document options"
            >
              <MoreHorizontal className="w-4 h-4" />
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-44 bg-white border border-slate-200 rounded-xl">
              <DropdownMenuItem
                className="flex items-center gap-2 cursor-pointer text-slate-600"
                onClick={copyDocLink}
              >
                <Link2 className="w-3.5 h-3.5 text-slate-400" />
                <span>{linkCopied ? 'Copied!' : 'Copy link'}</span>
              </DropdownMenuItem>
              <DropdownMenuSeparator className="bg-slate-100" />
              <DropdownMenuItem
                className="flex items-center gap-2 cursor-pointer text-red-600 focus:text-red-600"
                onClick={handleDeleteDocument}
              >
                <Trash2 className="w-3.5 h-3.5" />
                <span>Delete document</span>
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          )}
        </div>
      </div>

      {/* ── Main area ── */}
      <div className="relative flex min-h-0 flex-1 overflow-hidden">
        <div className="min-h-0 flex-1 overflow-y-auto scrollbar-minimal">
          <div className="mx-auto max-w-3xl px-8 py-10">
            {isAutoRecap ? (
              <DocumentViewHeader
                workspaceId={workspaceId}
                workspaceName={workspaceName}
                folderId={folderId}
                folderName={folderName}
                title={title}
                autoGenerated
                pageUrl={doc.pageUrl}
                updatedAt={doc.updatedAt}
                captureTags={captureTags}
                editable
                onTitleChange={setTitle}
                onTitleBlur={() => persist(title, doc.content)}
                actions={(
                  <DocumentHeaderActions
                    saved={savedFlash}
                    savedLabel="Saved"
                    copied={linkCopied}
                    onShare={copyDocLink}
                    menuOpen={recapMenuOpen}
                    onMenuToggle={() => setRecapMenuOpen(v => !v)}
                    onMenuClose={() => setRecapMenuOpen(false)}
                    menuItems={[
                      { icon: Link2, label: linkCopied ? 'Copied!' : 'Copy link', action: copyDocLink },
                      { icon: Trash2, label: 'Delete', action: handleDeleteDocument, danger: true },
                    ]}
                  />
                )}
              />
            ) : (
              <>
            <input
              type="text"
              value={title}
              onChange={e => setTitle(e.target.value)}
              onBlur={() => persist(title, doc.content)}
              placeholder="Title of this note"
              aria-label="Document title"
              className="w-full text-3xl font-bold text-slate-800 placeholder:text-slate-300 bg-transparent border-0 outline-none focus:ring-0 mb-1 leading-tight"
            />

            <div className="flex items-center gap-3 mb-6 pb-6 border-b border-slate-200">
              <div className="w-8 h-8 rounded-full bg-[#EDEBE8] border-2 border-white flex items-center justify-center text-xs font-bold text-[#37352F]">
                Y
              </div>
              <button
                type="button"
                onClick={() => setShowShare(true)}
                className="flex items-center gap-1.5 text-sm text-slate-400 hover:text-[#37352F] transition-colors cursor-pointer"
              >
                <Share2 className="w-3.5 h-3.5" />
                Share
              </button>
            </div>
              </>
            )}

            <FolderDocumentEditor
              content={editorContent}
              onChange={handleContentChange}
              className={isAutoRecap ? 'auto-recap-document' : undefined}
              recapMode={isAutoRecap}
            />

            {isAutoRecap && !notesLoading && pageNotes.length > 0 && (
              <RecapDocEnhancements
                workspaceId={workspaceId}
                docId={documentId}
                notes={pageNotes}
                recapHtml={editorContent}
              />
            )}

            {isAutoRecap && (
              <RecapFooterActions
                pageUrl={doc.pageUrl}
                onRegenerate={handleRegenerate}
                regenerating={regenerating}
                recapStale={doc.recapStale}
              />
            )}
          </div>
        </div>

        {isAutoRecap && (
          <RecapContextPanel
            doc={doc}
            notes={pageNotes}
            contentHtml={editorContent}
            loadingNotes={notesLoading}
            onRegenerate={handleRegenerate}
            regenerating={regenerating}
            collapsed={panelCollapsed}
            onCollapsedChange={setPanelCollapsed}
          />
        )}

        {!isAutoRecap && (
        <AnimatePresence>
          {showComments && (
            <motion.div
              initial={{ width: 0, opacity: 0 }}
              animate={{ width: 320, opacity: 1 }}
              exit={{ width: 0, opacity: 0 }}
              transition={{ duration: 0.2, ease: 'easeInOut' }}
              className="border-l border-slate-200 bg-white flex flex-col overflow-hidden shrink-0"
            >
              <div className="flex items-center justify-between px-4 py-3 border-b border-slate-100">
                <h3 className="text-sm font-semibold text-slate-700">Comments</h3>
                <button
                  type="button"
                  onClick={() => setShowComments(false)}
                  className="w-6 h-6 rounded flex items-center justify-center text-slate-400 hover:text-slate-600 cursor-pointer"
                >
                  <X className="w-3.5 h-3.5" />
                </button>
              </div>

              <div className="flex-1 overflow-y-auto p-4 space-y-3">
                {comments.length === 0 && (
                  <p className="text-sm text-slate-400 text-center py-8">
                    No comments yet. Start a conversation about this document.
                  </p>
                )}
                {comments.map(c => (
                  <div key={c.id} className="group">
                    <div className="flex items-start gap-2.5">
                      <div className="w-7 h-7 rounded-full bg-[#EDEBE8] flex items-center justify-center text-xs font-bold text-[#37352F] shrink-0 mt-0.5">
                        {c.author[0]}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <span className="text-xs font-semibold text-slate-700">{c.author}</span>
                          <span className="text-[10px] text-slate-400">{timeSince(c.time)}</span>
                          <button
                            type="button"
                            onClick={() => deleteComment(c.id)}
                            className="ml-auto opacity-0 group-hover:opacity-100 text-slate-300 hover:text-red-400 transition-all cursor-pointer"
                          >
                            <X className="w-3 h-3" />
                          </button>
                        </div>
                        <p className="text-sm text-slate-600 mt-0.5 leading-relaxed">{c.text}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              <div className="p-3 border-t border-slate-100">
                <div className="flex items-center gap-2">
                  <input
                    ref={commentInputRef}
                    type="text"
                    value={commentDraft}
                    onChange={e => setCommentDraft(e.target.value)}
                    onKeyDown={e => { if (e.key === 'Enter') addComment() }}
                    placeholder="Write a comment..."
                    className="flex-1 text-sm border border-slate-200 rounded-lg px-3 py-2 bg-slate-50 outline-none focus:border-[#C4D4E4] focus:bg-white transition-colors"
                  />
                  <button
                    type="button"
                    onClick={addComment}
                    disabled={!commentDraft.trim()}
                    className="w-8 h-8 rounded-lg bg-[#191919] text-white flex items-center justify-center disabled:opacity-40 cursor-pointer hover:bg-[#150C00] transition-colors shrink-0"
                  >
                    <Send className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
        )}
      </div>

      {/* ── Share modal — honest: copy link only, no fake invites ── */}
      <AnimatePresence>
        {showShare && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[60] bg-black/30 flex items-center justify-center"
            onClick={() => setShowShare(false)}
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              onClick={e => e.stopPropagation()}
              className="bg-white rounded-2xl border border-slate-200 w-full max-w-md p-6 mx-4"
            >
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-lg font-semibold text-slate-800">Share this document</h3>
                <button
                  type="button"
                  onClick={() => setShowShare(false)}
                  className="text-slate-400 hover:text-slate-600 cursor-pointer"
                  aria-label="Close"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              <p className="text-sm text-slate-500 mb-4">
                Documents are private to your account. Real-time collaboration
                isn&apos;t available yet — you can copy a link for your own
                bookmarks or notes.
              </p>

              <div className="flex gap-2">
                <input
                  readOnly
                  value={typeof window !== 'undefined' ? window.location.href : ''}
                  onFocus={e => e.currentTarget.select()}
                  aria-label="Document link"
                  className="flex-1 min-w-0 text-sm border border-slate-200 rounded-lg px-3 py-2.5 bg-slate-50 text-slate-600 outline-none focus:border-[#C4D4E4] transition-colors"
                />
                <Button
                  onClick={copyDocLink}
                  className="bg-[#191919] hover:bg-[#150C00] text-white cursor-pointer shrink-0"
                >
                  {linkCopied ? 'Copied' : 'Copy link'}
                </Button>
              </div>

              <div className="mt-4 pt-4 border-t border-slate-100">
                <p className="text-xs font-medium text-slate-500 mb-2">People with access</p>
                <div className="flex items-center gap-3 py-2">
                  <div className="w-8 h-8 rounded-full bg-[#EDEBE8] flex items-center justify-center text-xs font-bold text-[#37352F]">Y</div>
                  <div className="flex-1">
                    <p className="text-sm font-medium text-slate-700">You</p>
                    <p className="text-xs text-slate-400">Owner</p>
                  </div>
                  <span className="text-xs text-slate-400 bg-slate-50 px-2 py-0.5 rounded">Owner</span>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
