'use client'

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import {
  Loader2, ExternalLink, Trash2, Copy, ArrowLeft,
} from 'lucide-react'
import { getDocumentById, upsertFolderDocument, deleteFolderDocument, type FolderDocument } from '@/lib/workspace-library'
import { loadWorkspaceFolders } from '@/lib/workspace-folders'
import { getWorkspaceName } from '@/lib/workspaces'
import { normalizeRecapContent, regenerateRecapFromNotesAsync } from '@/lib/auto-recap'
import { buildRecapHeaderTags } from '@/lib/recap-meta'
import { useRecapNotes } from '@/lib/use-recap-notes'
import FolderDocumentEditor from '@/components/documents/FolderDocumentEditor'
import DocumentViewHeader from '@/components/documents/DocumentViewHeader'
import DocumentHeaderActions from '@/components/documents/DocumentHeaderActions'
import RecapContextPanel from '@/components/documents/RecapContextPanel'
import RecapFooterActions from '@/components/documents/RecapFooterActions'

export default function DocPage() {
  const { workspaceId, docId } = useParams<{ workspaceId: string; docId: string }>()
  const router = useRouter()

  const [doc,       setDoc]       = useState<FolderDocument | null>(null)
  const [title,     setTitle]     = useState('')
  const [saved,     setSaved]     = useState(false)
  const [loading,   setLoading]   = useState(true)
  const [menuOpen,  setMenuOpen]  = useState(false)
  const [copied,    setCopied]    = useState(false)
  const [folderName, setFolderName] = useState('Folder')
  const [regenerating, setRegenerating] = useState(false)
  const [panelCollapsed, setPanelCollapsed] = useState(false)
  const menuRef = useRef<HTMLDivElement>(null)

  const workspaceName = getWorkspaceName(workspaceId)
  const { notes: pageNotes, loading: notesLoading } = useRecapNotes(workspaceId, doc?.pageUrl)

  useEffect(() => {
    const d = getDocumentById(docId)
    if (!d) { router.replace(`/app/${workspaceId}/dashboard`); return }
    setDoc(d); setTitle(d.title); setLoading(false)
    const folders = loadWorkspaceFolders()
    const folder = folders.find(f => f.id === d.folderId)
    if (folder) setFolderName(folder.name)
  }, [docId, workspaceId, router])

  useEffect(() => {
    function onDown(e: MouseEvent) {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) setMenuOpen(false)
    }
    document.addEventListener('mousedown', onDown)
    return () => document.removeEventListener('mousedown', onDown)
  }, [])

  function persist(nextTitle: string, nextContent: string) {
    if (!doc) return
    const updated: FolderDocument = {
      ...doc,
      title: nextTitle.trim() || 'Untitled',
      content: nextContent,
      updatedAt: Date.now(),
      recapStale: doc.autoGenerated ? true : doc.recapStale,
    }
    setDoc(updated); upsertFolderDocument(updated)
    setSaved(true); setTimeout(() => setSaved(false), 1400)
  }

  const handleContentChange = useCallback((html: string) => {
    if (!doc) return
    const updated: FolderDocument = {
      ...doc,
      title: title.trim() || 'Untitled',
      content: html,
      updatedAt: Date.now(),
      recapStale: doc.autoGenerated ? true : doc.recapStale,
    }
    setDoc(updated)
    upsertFolderDocument(updated)
    setSaved(true)
    setTimeout(() => setSaved(false), 1400)
  }, [doc, title])

  function handleTitleBlur() { persist(title, doc?.content ?? '') }

  const handleRegenerate = useCallback(async () => {
    if (!doc?.pageUrl) return
    setRegenerating(true)
    try {
      const updated = await regenerateRecapFromNotesAsync(doc, workspaceName, pageNotes)
      upsertFolderDocument(updated)
      setDoc(updated)
      setTitle(updated.title)
    } finally {
      setRegenerating(false)
    }
  }, [doc, workspaceName, pageNotes])

  const captureTags = useMemo(
    () => buildRecapHeaderTags(doc?.pageUrl, pageNotes),
    [doc?.pageUrl, pageNotes],
  )

  const isAutoRecap = !!doc?.autoGenerated
  const editorContent = useMemo(() => {
    if (!doc) return ''
    return isAutoRecap ? normalizeRecapContent(doc.content, pageNotes) : doc.content
  }, [doc, isAutoRecap, pageNotes])

  useEffect(() => {
    if (!doc?.autoGenerated || notesLoading || pageNotes.length === 0) return
    const normalized = normalizeRecapContent(doc.content, pageNotes)
    if (normalized === doc.content) return
    const updated = { ...doc, content: normalized }
    upsertFolderDocument(updated)
    setDoc(updated)
  }, [doc, pageNotes, notesLoading])

  async function handleShare() {
    try {
      await navigator.clipboard.writeText(window.location.href)
      setCopied(true)
      setTimeout(() => setCopied(false), 1800)
    } catch { /* clipboard unavailable */ }
  }

  function handleDelete() {
    if (!doc) return
    deleteFolderDocument(doc.id)
    router.replace(`/app/${workspaceId}/folder/${doc.folderId}`)
  }

  function handleDuplicate() {
    if (!doc) return
    const now = Date.now()
    const copy: FolderDocument = {
      ...doc,
      id: `doc-${now}-${Math.random().toString(36).slice(2, 7)}`,
      title: doc.title + ' (copy)',
      content: doc.content,
      autoGenerated: false,
      pageUrl: undefined,
      createdAt: now,
      updatedAt: now,
    }
    upsertFolderDocument(copy)
    router.push(`/app/${workspaceId}/doc/${copy.id}`)
  }

  if (loading) return (
    <div className="flex items-center justify-center h-40">
      <Loader2 className="w-5 h-5 animate-spin text-muted-foreground" />
    </div>
  )
  if (!doc) return null

  const panelOpen = isAutoRecap && !panelCollapsed

  return (
    <div className="relative flex h-full min-h-0 flex-col overflow-hidden bg-background">
      <Link
        href={`/app/${workspaceId}/folder/${doc.folderId}`}
        className="absolute top-3 left-8 z-30 inline-flex max-w-[min(100vw-12rem,20rem)] items-center gap-1.5 text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
      >
        <ArrowLeft className="h-3.5 w-3.5 shrink-0" aria-hidden />
        <span className="truncate">All documents in {folderName}</span>
      </Link>

      <div className="flex min-h-0 flex-1 overflow-hidden">
        <div className="min-h-0 flex-1 overflow-y-auto scrollbar-minimal">
          <div
            className="mx-auto max-w-3xl pt-14 pb-24"
            style={{ paddingLeft: 80, paddingRight: panelOpen ? 32 : 80 }}
          >
            <DocumentViewHeader
            workspaceId={workspaceId}
            workspaceName={workspaceName}
            folderId={doc.folderId}
            folderName={folderName}
            title={title}
            autoGenerated={isAutoRecap}
            pageUrl={doc.pageUrl}
            updatedAt={doc.updatedAt}
            captureTags={isAutoRecap ? captureTags : undefined}
            editable
            onTitleChange={setTitle}
            onTitleBlur={handleTitleBlur}
            actions={(
              <div ref={menuRef}>
                <DocumentHeaderActions
                  saved={saved}
                  copied={copied}
                  onShare={handleShare}
                  menuOpen={menuOpen}
                  onMenuToggle={() => setMenuOpen(v => !v)}
                  onMenuClose={() => setMenuOpen(false)}
                  menuItems={[
                    { icon: ExternalLink, label: 'Open in folder', action: () => router.push(`/app/${workspaceId}/folder/${doc.folderId}`) },
                    { icon: Copy, label: 'Duplicate', action: handleDuplicate },
                    { icon: Trash2, label: 'Delete', action: handleDelete, danger: true },
                  ]}
                />
              </div>
            )}
          />

          <FolderDocumentEditor
            content={editorContent}
            onChange={handleContentChange}
            className={isAutoRecap ? 'auto-recap-document' : undefined}
            recapMode={isAutoRecap}
          />

          {isAutoRecap && (
            <RecapFooterActions
              pageUrl={doc.pageUrl}
              onRegenerate={handleRegenerate}
              regenerating={regenerating}
              recapStale={doc.recapStale}
            />
          )}
          </div>
        </div>

        {isAutoRecap && (
          <RecapContextPanel
            doc={doc}
            notes={pageNotes}
            contentHtml={editorContent}
            loadingNotes={notesLoading}
            onRegenerate={handleRegenerate}
            regenerating={regenerating}
            collapsed={panelCollapsed}
            onCollapsedChange={setPanelCollapsed}
          />
        )}
      </div>
    </div>
  )
}
